### ISSUE TITLE
Alternate glyph paths

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/alt-hack#1]
Propose the following paths from the root of the repository for each Unicode position:

```
glyphs
    ├── uXXX
          ├── bold
          ├── bolditalic
          ├── italic
          ├── regular
```

with the *.glif file under the respective variant directory.  For ASCII set glyphs, we will need to consider another level of subdirectories that include manual hinting modifications when they are used in the main set.

This won't support multiple glyphs at a single Unicode code point.  How do we address that? With an additional string after the Unicode path like this maybe?

```
glyphs
    ├── uXXX-slashed
          ├── bold
          ├── bolditalic
          ├── italic
          ├── regular
    ├── uXXX-dotted
          ├── bold
          ├── bolditalic
          ├── italic
          ├── regular
```

Thoughts @jublo @burodepeper?

**Comment by mynetx** [comment]
Sounds feasible, `uXXX-slashed`.

**Comment by chrissimpkins** [comment]
:+1:
