### ISSUE TITLE
U+00EC i igrave slab alternate style - add glyph

### ISSUE THREAD

**Issue by tri-nga** [source-foundry/alt-hack#13]
(u00EC) igrave slab style to complete the i slab variant.

**Comment by chrissimpkins** [comment]
![i_reg](https://user-images.githubusercontent.com/4249591/32996356-9f8794ac-cd4f-11e7-9e13-cc27b14219cd.png)
![i_italic](https://user-images.githubusercontent.com/4249591/32996357-a16ce2ae-cd4f-11e7-9a0f-7978f60ccb42.png)
![i_bold](https://user-images.githubusercontent.com/4249591/32996359-a32071ce-cd4f-11e7-8a51-9416e0c82476.png)
![i_bolditalic](https://user-images.githubusercontent.com/4249591/32996361-a5010076-cd4f-11e7-8688-5d375f2148c7.png)

**Comment by chrissimpkins** [comment]
added by @dok42 in https://github.com/source-foundry/alt-hack/commit/b619d6945687ec89cb62775c0e09b9405682b4eb
