### ISSUE TITLE
Visual display of the alternate glyphs

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/alt-hack#2]
Propose:

- black on white screenshot of the glyphs x 4 variants at font size of ____ that is included in a Markdown file at the Unicode label directory root of the Unicode code point.

**Comment by chrissimpkins** [comment]
Taking screenshots of black on white with OSX preview of the *.glif file and then resizing to height="60" in html.  Adding this to README.md in each glyph subdirectory

**Comment by mynetx** [comment]
Sample?

**Comment by chrissimpkins** [comment]
https://github.com/source-foundry/alt-hack/blob/master/glyphs/u0030-forwardslash/README.md

**Comment by mynetx** [comment]
Perfect. Suggest exact steps for contributors to take these pictures so they are all the same?

**Comment by chrissimpkins** [comment]
Thoughts?  This was a suggestion to get feedback.  We can do it however felt to be best.  Could go as detailed as a website for display, could make it as simple as this approach with four images inside the individual glyph repo.
