### ISSUE TITLE
Forward slashed zero alternate

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/alt-hack#3]
![slashed_zero](https://user-images.githubusercontent.com/4249591/31209176-383a2862-a957-11e7-99a3-7a4ef89bf68d.png)

cc:@jublo @burodepeper

**Comment by chrissimpkins** [comment]
added regular variant in https://github.com/source-foundry/alt-hack/commit/958a1e449141a341d46fec66eaf8607c7b5f2db3

**Comment by burodepeper** [comment]
What does it look like at 'normal' sizes? My instinct says that the slant might have to be a bit more horizontal when smaller.

**Comment by chrissimpkins** [comment]
Will take a look at the compare typefaces tool to see how other faces are slanting it.  Can push images of smaller sizes this evening.  Feel free to grab the glif file and modify, push.  This was just to get the conversation started.

**Comment by chrissimpkins** [comment]
![forward_slash_8](https://user-images.githubusercontent.com/4249591/31258853-3c737f82-aa10-11e7-8ed2-8143a0cd1900.png)

**Comment by chrissimpkins** [comment]
Here are some examples from other typefaces using your compare-typefaces tool:

![m_anonymous](https://user-images.githubusercontent.com/4249591/31258930-dea52cba-aa10-11e7-9fc7-8965b3e33d58.png)
![m_inconsol](https://user-images.githubusercontent.com/4249591/31258932-e228ad30-aa10-11e7-87cd-329c46bd3f99.png)
![menlo](https://user-images.githubusercontent.com/4249591/31258933-e442aecc-aa10-11e7-8c78-31094f348dbb.png)
![monaco](https://user-images.githubusercontent.com/4249591/31258936-e6f695fc-aa10-11e7-9961-fe8facf0a69b.png)

**Comment by chrissimpkins** [comment]
@burodepeper @jublo think we should decrease width of the line a bit?  Seems to limit white space inside the zero as you get to smaller sizes.  Angle does seem a bit more upright than in other faces.  Probably for that reason, though subjectively I like it a bit more upright than angled.  Thoughts?

**Comment by burodepeper** [comment]
![schermafbeelding 2017-10-06 om 17 00 45](https://user-images.githubusercontent.com/3703530/31284121-f5321216-aab7-11e7-88be-77b8313eb41c.png)

Threw together the image above real quick. I wanted to demonstrate what I think the minimum distance should be from where the slant connects to the outline of the circle. The height of the horizontal bars is the same as the thickness of the horizontal stroke of the font. This should ensure that there's always as much breathing room as there is line thickness, independent of the font size.

**Comment by chrissimpkins** [comment]
👍  not by an editor at the moment to take a look where this is presently.  Will take a look over the weekend unless @jublo wants to work on these.  

Suggest the same approach with the bold sets?  This will push the line a bit more horizontal there.

**Comment by burodepeper** [comment]
> Suggest the same approach with the bold sets? This will push the line a bit more horizontal there.

My thoughts exactly. Shouldn't be an issue. Same for italics.

**Comment by chrissimpkins** [comment]
It looks like most other fonts have a greater angle in the line fill for oblique variants at a given weight relative to the non-oblique.  Thoughts about that approach?  Any thoughts about maintaining consistency in the internal line angle between regular and oblique with only the outside circular shape changing angle?

**Comment by burodepeper** [comment]
1) Don't give a crap.
2) ~~Same approach as above, but determine the distance (and therefore the angle) on the weight of bold instead of regular.~~

Oh wait, you talked about italics. I think the slant should change along with the angle of the italics. I've been trying to fit everything in my own typeface to the same internal angles, but you just end up making things to hard on yourself. Readability is more important, so the slant should change to accommodate that.

**Comment by chrissimpkins** [comment]
I'll take that dismissal as your preference for an increase in the angle relative to vertical in the oblique sets weight for weight... ;)

**Comment by chrissimpkins** [comment]
<img src="https://user-images.githubusercontent.com/4249591/31325182-35ab6c76-ac88-11e7-906e-6fd295364f10.png" height="60">

**Comment by chrissimpkins** [comment]
all variants added to repository
