### ISSUE TITLE
Backward slashed zero alternate

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/alt-hack#4]
![backslash_zero](https://user-images.githubusercontent.com/4249591/31209249-ad030eac-a957-11e7-92b0-9c398b6637a3.png)

cc: @jublo @burodepeper

**Comment by chrissimpkins** [comment]
added regular variant in https://github.com/source-foundry/alt-hack/commit/30be4ef5c7540626af414be230a627e8975f4d14

**Comment by chrissimpkins** [comment]
@jublo you mentioned that you wanted to work on this.  This is only here to begin the conversation about new shapes for the zero.  If still an interest, feel free to grab it and go to town.   Would make sense to work on both this and the forward slashed version simultaneously because you can mirror their designs.  If you don't have time for it now, I will add versions across all of the sets over the upcoming week.  Feel free to modify anything that I push.

**Comment by burodepeper** [comment]
For the sake of simplicity, I suggest that this is going to simply be a reversed copy (as a component) of the normal slashed zero.

**Comment by chrissimpkins** [comment]
@burodepeper Agree with you David.  That is what it currently is and it would make most sense for whoever takes these glyphs on to simply complete all four sets of both shapes simultaneously.  There is a simple "mirror image/horizontal rotation" button in Glyphs that makes this a sub-second change in design :)

**Comment by burodepeper** [comment]
> There is a simple "mirror image/horizontal rotation" button in Glyphs that makes this a sub-second change in design :)

I've been using that a lot these days. ; )

**Comment by chrissimpkins** [comment]
<img src="https://user-images.githubusercontent.com/4249591/31325366-22dd1048-ac8a-11e7-9029-ff19d53c6903.png" height="60">

**Comment by chrissimpkins** [comment]
All four variants added
